---
title: "code"
author: "Tim"
date: "2024-01-18"
output: html_document
---

```{r}
#liquid
#add all ICs
library(dplyr)
rawdata <- read.csv(file = 'C:/Users/timothy/Documents/GWAS_data/dairy/IGF1data.csv')
dataa <- rawdata %>%
  select(eid, rsfMRI_Component2,	rsfMRI_Component3, rsfMRI_Component4,	rsfMRI_Component6,rsfMRI_Component8,rsfMRI_Component11, rsfMRI_Component12,	rsfMRI_Component15,	rsfMRI_Component16,	rsfMRI_Component17,	rsfMRI_Component18,	rsfMRI_Component19, rsfMRI_Component21
)
colnames(dataa)[1]<-"EID"
datab <-read.csv(file = 'C:\\Users\\timothy\\OneDrive\\Documents\\ISU\\food_project\\data\\food_liquids.csv')
df<-merge(dataa,datab,by="EID")
rm(dataa)
rm(datab)
rm(rawdata)
# remove invalid values
# wanted variables
variables1 <- c("Water_1.0", "Water_2.0", "Water_3.0", "Water_4.0", "Water_0.0",
               "LowCalorie_1.0", "LowCalorie_2.0", "LowCalorie_3.0", "LowCalorie_4.0", "LowCalorie_0.0",
               "Fizzy_1.0", "Fizzy_2.0", "Fizzy_3.0", "Fizzy_4.0", "Fizzy_0.0",
               "Squash_1.0", "Squash_2.0", "Squash_3.0", "Squash_4.0", "Squash_0.0",
               "OrangeJuice_1.0", "OrangeJuice_2.0", "OrangeJuice_3.0", "OrangeJuice_4.0", "OrangeJuice_0.0",
               "GrapeJuice_1.0", "GrapeJuice_2.0", "GrapeJuice_3.0", "GrapeJuice_4.0", "GrapeJuice_0.0",
               "FruitVegeJuice_1.0", "FruitVegeJuice_2.0", "FruitVegeJuice_3.0", "FruitVegeJuice_4.0", "FruitVegeJuice_0.0",
               "FruitSmoothie_1.0", "FruitSmoothie_2.0", "FruitSmoothie_3.0", "FruitSmoothie_4.0", "FruitSmoothie_0.0",
               "DairySmoothie_1.0", "DairySmoothie_2.0", "DairySmoothie_3.0", "DairySmoothie_4.0", "DairySmoothie_0.0", 
               "InstantCoffee_1.0",	"InstantCoffee_2.0", "InstantCoffee_3.0", "InstantCoffee_4.0", "InstantCoffee_0.0",
               "FilterCoffee_1.0", "FilterCoffee_2.0", "FilterCoffee_3.0", "FilterCoffee_4.0", "FilterCoffee_0.0", 
               "Cappuccino_1.0", "Cappuccino_2.0", "Cappuccino_3.0", "Cappuccino_4.0", "Cappuccino_0.0", 
               "Latte_1.0", "Latte_2.0", "Latte_3.0", "Latte_4.0", "Latte_0.0", 
               "Espresso_1.0", "Espresso_2.0", "Espresso_3.0", "Espresso_4.0", "Espresso_0.0", 
               "OtherCoffee_1.0", "OtherCoffee_2.0", "OtherCoffee_3.0", "OtherCoffee_4.0", "OtherCoffee_0.0",
               "LowCalorieHotChocolate_1.0", "LowCalorieHotChocolate_2.0", "LowCalorieHotChocolate_3.0", 
               "LowCalorieHotChocolate_4.0", "LowCalorieHotChocolate_0.0", 
               "HotChocolate_1.0", "HotChocolate_2.0", "HotChocolate_3.0", "HotChocolate_4.0", "HotChocolate_0.0")
variables2 <- c("StandTea_1.0", "StandTea_2.0", "StandTea_3.0", "StandTea_4.0", "StandTea_0.0", "RooibosTea_1.0", "RooibosTea_2.0", "RooibosTea_3.0", "RooibosTea_4.0", "RooibosTea_0.0", "GreenTea_1.0", "GreenTea_2.0", "GreenTea_3.0", "GreenTea_4.0", "GreenTea_0.0", "HerbalTea_1.0", "HerbalTea_2.0", "HerbalTea_3.0", "HerbalTea_4.0", "HerbalTea_0.0", "OtherTea_1.0", "OtherTea_2.0", "OtherTea_3.0", "OtherTea_4.0", "OtherTea_0.0")
# consumption variables (can be only 0 or 1)
cvariables <- c("CoffeeConsume_1.0", "CoffeeConsume_2.0",	"CoffeeConsume_3.0",	"CoffeeConsume_4.0",	"CoffeeConsume_0.0", "TeaConsume_1.0",	"TeaConsume_2.0",	"TeaConsume_3.0",	"TeaConsume_4.0",	"TeaConsume_0.0")
# invalid values are with decimal (replace all non-integer (decimal) values in the specified columns of the df data frame with NA)
df[, variables1] <- lapply(df[, variables1], function(x) ifelse(x == floor(x), x, NA))
# invalid values are with decimal (replace all non-integer (decimal) values in the specified columns of the df data frame with NA)
df[, variables2] <- lapply(df[, variables2], function(x) ifelse(x == floor(x), x, NA))
# define valid values
valid_jvalues <- c(0, 1, 2, 3, 4, 5, 555, 600)
valid_j2values <-c(0, 1, 2, 3, 4, 5, 600)
valid_cvalues <- c(0, 1)
# only keep valid values for wanted variables
df[, variables1] <- lapply(df[, variables1], function(x) ifelse(x %in% valid_jvalues, x, NA))
df[, variables2] <- lapply(df[, variables2], function(x) ifelse(x %in% valid_j2values, x, NA))
# only keep valid values for consumption variables
df[, cvariables] <- lapply(df[, cvariables], function(x) ifelse(x %in% valid_cvalues, x, NA))

# remove unwanted variables
# variables to remove
variables_to_remove <- c("AddMilkFilterCoffee_1.0", "AddMilkFilterCoffee_2.0", "AddMilkFilterCoffee_3.0", 
                         "AddMilkFilterCoffee_4.0", "AddMilkFilterCoffee_0.0", "AddMilkCoffee_1.0", 
                         "AddMilkCoffee_2.0", "AddMilkCoffee_3.0", "AddMilkCoffee_4.0", "AddMilkCoffee_0.0",
                         "SugarAddtoCoffee_1.0", "SugarAddtoCoffee_2.0", "SugarAddtoCoffee_3.0", 
                         "SugarAddtoCoffee_4.0", "SugarAddtoCoffee_0.0", "ArtificialSweettoCoffee_1.0", "ArtificialSweettoCoffee_2.0",
                         "ArtificialSweettoCoffee_3.0", "ArtificialSweettoCoffee_4.0", "ArtificialSweettoCoffee_0.0", 
                         "AddMilkStandTea_1.0", "AddMilkStandTea_2.0", "AddMilkStandTea_3.0", "AddMilkStandTea_4.0", 
                         "AddMilkStandTea_0.0", "DecaffeinTea_1.0", "DecaffeinTea_2.0", "DecaffeinTea_3.0", 
                         "DecaffeinTea_4.0", "DecaffeinTea_0.0", "AddMilkRooibos_1.0", "AddMilkRooibos_2.0", 
                         "AddMilkRooibos_3.0", "AddMilkRooibos_4.0", "AddMilkRooibos_0.0", "SugarToTea_1.0", 
                         "SugarToTea_2.0", "SugarToTea_3.0", "SugarToTea_4.0", "SugarToTea_0.0", "ArtificialSweetTea_1.0", 
                         "ArtificialSweetTea_2.0", "ArtificialSweetTea_3.0", "ArtificialSweetTea_4.0", "ArtificialSweetTea_0.0")
df <- df %>% select(-one_of(variables_to_remove))
# replace "555" and "600"
df[, variables1] <- lapply(df[, variables1], function(x) { 
    x <- ifelse(x == 555, 0.5, x) 
    x <- ifelse(x == 600, 6, x)
    x
})
df[, variables2] <- lapply(df[, variables2], function(x) { 
    x <- ifelse(x == 600, 6, x)
    x
})
rm(valid_cvalues, valid_jvalues, variables_to_remove, valid_j2values)

# List of variables
variables <- c("Water", "LowCalorie", "Fizzy", "Squash", "OrangeJuice", "GrapeJuice", "FruitVegeJuice", "FruitSmoothie", "DairySmoothie", "InstantCoffee", "FilterCoffee", "Cappuccino", "Latte", "Espresso", "OtherCoffee", "LowCalorieHotChocolate", "HotChocolate", "StandTea", "RooibosTea",  "GreenTea", "HerbalTea", "OtherTea")
# Suffix for each variable
suffix <- c("_1.0", "_2.0", "_3.0", "_4.0", "_0.0")
# Loop through all variables
for (var in variables) {
  # Generate the column names for each variable
  cols <- paste0(var, suffix)
  # Check if columns exist in the dataframe
  if (all(cols %in% colnames(df))) {
    # Calculate the mean
    df[[paste0(var, "_mean")]] <- rowMeans(df[, cols], na.rm = TRUE)
  }
}
rm(cols, suffix, var, variables)

# merge juice and coffee
# 1. merge juice:
juice_vars <- c("Fizzy", "Squash", "OrangeJuice", "GrapeJuice", 
                "FruitVegeJuice", "FruitSmoothie", "DairySmoothie")
suffixes <- c("1.0", "2.0", "3.0", "4.0", "0.0")

# calculate juice_* variables
for(suffix in suffixes) {
  columns <- paste(juice_vars, suffix, sep="_") # creates a vector of column names with current suffix
  new_column <- paste("juice", suffix, sep="_") # creates a name for new column
  df[[new_column]] <- apply(df[, columns], 1, function(x) {
    if (all(is.na(x))) {
      return(NA)
    } else {
      return(sum(x, na.rm = TRUE))
    }
  })
}

# Calculate row mean of juice
df$juice_mean <- apply(df[, paste("juice", suffixes, sep="_")], 1, function(x) {
    if (all(is.na(x))) {
      return(NA)
    } else {
      return(mean(x, na.rm = TRUE))
    }
  })

# Remove juice_* columns
df <- df[ , !(names(df) %in% paste("juice", suffixes, sep="_"))]
rm(columns, juice_vars, new_column, suffix)

# 2. merge coffee:
coffee_vars <- c("InstantCoffee", "FilterCoffee", "Cappuccino", "Latte", 
                "Espresso", "OtherCoffee")
# calculate coffee_* variables
for(suffix in suffixes) {
  columns <- paste(coffee_vars, suffix, sep="_") # creates a vector of column names with current suffix
  new_column <- paste("coffee", suffix, sep="_") # creates a name for new column
  df[[new_column]] <- apply(df[, columns], 1, function(x) {
    if (all(is.na(x))) {
      return(NA)
    } else {
      return(sum(x, na.rm = TRUE))
    }
  })
}

# Calculate row mean of coffee
df$coffee_mean <- apply(df[, paste("coffee", suffixes, sep="_")], 1, function(x) {
    if (all(is.na(x))) {
      return(NA)
    } else {
      return(mean(x, na.rm = TRUE))
    }
  })

# Remove coffee_* columns
df <- df[ , !(names(df) %in% paste("coffee", suffixes, sep="_"))]
rm(columns, coffee_vars, new_column, suffix)

# 3. merge tea:
tea_vars <- c("StandTea", "RooibosTea",  "GreenTea", "HerbalTea", "OtherTea")
# calculate tea_* variables
for(suffix in suffixes) {
  columns <- paste(tea_vars, suffix, sep="_") # creates a vector of column names with current suffix
  new_column <- paste("tea", suffix, sep="_") # creates a name for new column
  df[[new_column]] <- apply(df[, columns], 1, function(x) {
    if (all(is.na(x))) {
      return(NA)
    } else {
      return(sum(x, na.rm = TRUE))
    }
  })
}

# Calculate row mean of tea
df$tea_mean <- apply(df[, paste("tea", suffixes, sep="_")], 1, function(x) {
    if (all(is.na(x))) {
      return(NA)
    } else {
      return(mean(x, na.rm = TRUE))
    }
  })

# Remove tea_* columns
df <- df[ , !(names(df) %in% paste("tea", suffixes, sep="_"))]
rm(columns, tea_vars, new_column, suffix, suffixes)
write.csv(df, "C:\\Users\\timothy\\OneDrive\\Documents\\ISU\\food_project\\data\\data_for_test\\food_liquids.csv",na='',row.names=FALSE)
rm(list=ls())
```

```{r}
# meat_vege data 
#add all ICs
library(dplyr)
rawdata <- read.csv(file = 'C:/Users/timothy/Documents/GWAS_data/dairy/IGF1data.csv')
dataa <- rawdata %>%
  select(eid, rsfMRI_Component2,	rsfMRI_Component3, rsfMRI_Component4,	rsfMRI_Component6,rsfMRI_Component8,rsfMRI_Component11, rsfMRI_Component12,	rsfMRI_Component15,	rsfMRI_Component16,	rsfMRI_Component17,	rsfMRI_Component18,	rsfMRI_Component19, rsfMRI_Component21
)
colnames(dataa)[1]<-"EID"
datab <-read.csv(file = 'C:\\Users\\timothy\\OneDrive\\Documents\\ISU\\food_project\\data\\food_meat_vege.csv')
df<-merge(dataa,datab,by="EID")
rm(dataa)
rm(datab)
rm(rawdata)
# remove invalid values
# wanted variables
cvariables <- c("EggConsum_1.0","EggConsum_2.0","EggConsum_3.0","EggConsum_4.0","EggConsum_0.0","MeatConsum_1.0","MeatConsum_2.0","MeatConsum_3.0","MeatConsum_4.0","MeatConsum_0.0","FishConsum_1.0","FishConsum_2.0","FishConsum_3.0","FishConsum_4.0","FishConsum_0.0","VegeAlter_1.0","VegeAlter_2.0","VegeAlter_3.0","VegeAlter_4.0","VegeAlter_0.0","SpreadConsum_1.0","SpreadConsum_2.0","SpreadConsum_3.0","SpreadConsum_4.0","SpreadConsum_0.0","NoFatCook_1.0","NoFatCook_2.0","NoFatCook_3.0","NoFatCook_4.0","NoFatCook_0.0","VegeConsum_1.0","VegeConsum_2.0","VegeConsum_3.0","VegeConsum_4.0","VegeConsum_0.0","ButterAddPotato_1.0","ButterAddPotato_2.0","ButterAddPotato_3.0","ButterAddPotato_4.0","ButterAddPotato_0.0","FruitConsum_1.0","FruitConsum_2.0","FruitConsum_3.0","FruitConsum_4.0","FruitConsum_0.0")

# wanted variables
egg_variables <- c("WholeEgg_1.0","WholeEgg_2.0","WholeEgg_3.0","WholeEgg_4.0","WholeEgg_0.0","Omelette_1.0","Omelette_2.0","Omelette_3.0","Omelette_4.0","Omelette_0.0","EgginSandwich_1.0","EgginSandwich_2.0","EgginSandwich_3.0","EgginSandwich_4.0","EgginSandwich_0.0","ScotchEgg_1.0","ScotchEgg_2.0","ScotchEgg_3.0","ScotchEgg_4.0","ScotchEgg_0.0","OthEgg_1.0","OthEgg_2.0","OthEgg_3.0","OthEgg_4.0","OthEgg_0.0")

meat_variables <- c("Sausage_1.0","Sausage_2.0","Sausage_3.0","Sausage_4.0","Sausage_0.0","Beef_1.0","Beef_2.0","Beef_3.0","Beef_4.0","Beef_0.0","Pork_1.0","Pork_2.0","Pork_3.0","Pork_4.0","Pork_0.0","Lamb_1.0","Lamb_2.0","Lamb_3.0","Lamb_4.0","Lamb_0.0","CrumbPoultry_1.0","CrumbPoultry_2.0","CrumbPoultry_3.0","CrumbPoultry_4.0","CrumbPoultry_0.0","Poultry_1.0","Poultry_2.0","Poultry_3.0","Poultry_4.0","Poultry_0.0","Bacon_1.0","Bacon_2.0","Bacon_3.0","Bacon_4.0","Bacon_0.0","Ham_1.0","Ham_2.0","Ham_3.0","Ham_4.0","Ham_0.0","Liver_1.0","Liver_2.0","Liver_3.0","Liver_4.0","Liver_0.0","OthMeat_1.0","OthMeat_2.0","OthMeat_3.0","OthMeat_4.0","OthMeat_0.0")

fish_variables <- c("TinTuna_1.0","TinTuna_2.0","TinTuna_3.0","TinTuna_4.0","TinTuna_0.0","OilyFish_1.0","OilyFish_2.0","OilyFish_3.0","OilyFish_4.0","OilyFish_0.0","BreadFish_1.0","BreadFish_2.0","BreadFish_3.0","BreadFish_4.0","BreadFish_0.0","BatteredFish_1.0","BatteredFish_2.0","BatteredFish_3.0","BatteredFish_4.0","BatteredFish_0.0","WhiteFish_1.0","WhiteFish_2.0","WhiteFish_3.0","WhiteFish_4.0","WhiteFish_0.0","Prawns_1.0","Prawns_2.0","Prawns_3.0","Prawns_4.0","Prawns_0.0","LobsterCrab_1.0","LobsterCrab_2.0","LobsterCrab_3.0","LobsterCrab_4.0","LobsterCrab_0.0","Shellfish_1.0","Shellfish_2.0","Shellfish_3.0","Shellfish_4.0","Shellfish_0.0","OthFish_1.0","OthFish_2.0","OthFish_3.0","OthFish_4.0","OthFish_0.0")

vegeAlter_variables <- c("VegeSausage_1.0","VegeSausage_2.0","VegeSausage_3.0","VegeSausage_4.0","VegeSausage_0.0","Tofu_1.0","Tofu_2.0","Tofu_3.0","Tofu_4.0","Tofu_0.0","Quorn_1.0","Quorn_2.0","Quorn_3.0","Quorn_4.0","Quorn_0.0","OthVegeAlter_1.0","OthVegeAlter_2.0","OthVegeAlter_3.0","OthVegeAlter_4.0","OthVegeAlter_0.0")

vegetable_variables <- c("BakeBean_1.0","BakeBean_2.0","BakeBean_3.0","BakeBean_4.0","BakeBean_0.0","Pulse_1.0","Pulse_2.0","Pulse_3.0","Pulse_4.0","Pulse_0.0","FriedPotato_1.0","FriedPotato_2.0","FriedPotato_3.0","FriedPotato_4.0","FriedPotato_0.0","BoilPotato_1.0","BoilPotato_2.0","BoilPotato_3.0","BoilPotato_4.0","BoilPotato_0.0","MashPotato_1.0","MashPotato_2.0","MashPotato_3.0","MashPotato_4.0","MashPotato_0.0","MixVege_1.0","MixVege_2.0","MixVege_3.0","MixVege_4.0","MixVege_0.0","VegePiece_1.0","VegePiece_2.0","VegePiece_3.0","VegePiece_4.0","VegePiece_0.0","Coleslaw_1.0","Coleslaw_2.0","Coleslaw_3.0","Coleslaw_4.0","Coleslaw_0.0","SideSalad_1.0","SideSalad_2.0","SideSalad_3.0","SideSalad_4.0","SideSalad_0.0","Avocado_1.0","Avocado_2.0","Avocado_3.0","Avocado_4.0","Avocado_0.0","BroadBean_1.0","BroadBean_2.0","BroadBean_3.0","BroadBean_4.0","BroadBean_0.0","GreenBean_1.0","GreenBean_2.0","GreenBean_3.0","GreenBean_4.0","GreenBean_0.0","Beetroot_1.0","Beetroot_2.0","Beetroot_3.0","Beetroot_4.0","Beetroot_0.0","Broccoli_1.0","Broccoli_2.0","Broccoli_3.0","Broccoli_4.0","Broccoli_0.0","Butternut_1.0","Butternut_2.0","Butternut_3.0","Butternut_4.0","Butternut_0.0","Cabbage_1.0","Cabbage_2.0","Cabbage_3.0","Cabbage_4.0","Cabbage_0.0","Carrot_1.0","Carrot_2.0","Carrot_3.0","Carrot_4.0","Carrot_0.0","Cauliflower_1.0","Cauliflower_2.0","Cauliflower_3.0","Cauliflower_4.0","Cauliflower_0.0","Celery_1.0","Celery_2.0","Celery_3.0","Celery_4.0","Celery_0.0","Courgette_1.0","Courgette_2.0","Courgette_3.0","Courgette_4.0","Courgette_0.0","Cucumber_1.0","Cucumber_2.0","Cucumber_3.0","Cucumber_4.0","Cucumber_0.0","Garlic_1.0","Garlic_2.0","Garlic_3.0","Garlic_4.0","Garlic_0.0","Leek_1.0","Leek_2.0","Leek_3.0","Leek_4.0","Leek_0.0","Lettuce_1.0","Lettuce_2.0","Lettuce_3.0","Lettuce_4.0","Lettuce_0.0","Mushroom_1.0","Mushroom_2.0","Mushroom_3.0","Mushroom_4.0","Mushroom_0.0","Onion_1.0","Onion_2.0","Onion_3.0","Onion_4.0","Onion_0.0","Parsnip_1.0","Parsnip_2.0","Parsnip_3.0","Parsnip_4.0","Parsnip_0.0","Pea_1.0","Pea_2.0","Pea_3.0","Pea_4.0","Pea_0.0","Sweetpepper_1.0","Sweetpepper_2.0","Sweetpepper_3.0","Sweetpepper_4.0","Sweetpepper_0.0","Spinach_1.0","Spinach_2.0","Spinach_3.0","Spinach_4.0","Spinach_0.0","Sprouts_1.0","Sprouts_2.0","Sprouts_3.0","Sprouts_4.0","Sprouts_0.0","Sweetcorn_1.0","Sweetcorn_2.0","Sweetcorn_3.0","Sweetcorn_4.0","Sweetcorn_0.0","Sweetpotato_1.0","Sweetpotato_2.0","Sweetpotato_3.0","Sweetpotato_4.0","Sweetpotato_0.0","FreshTomato_1.0","FreshTomato_2.0","FreshTomato_3.0","FreshTomato_4.0","FreshTomato_0.0","TinTomato_1.0","TinTomato_2.0","TinTomato_3.0","TinTomato_4.0","TinTomato_0.0","Turnip_1.0","Turnip_2.0","Turnip_3.0","Turnip_4.0","Turnip_0.0","Watercress_1.0","Watercress_2.0","Watercress_3.0","Watercress_4.0","Watercress_0.0","OthVege_1.0","OthVege_2.0","OthVege_3.0","OthVege_4.0","OthVege_0.0")

fruit_variables <- c("StewedFruit_1.0","StewedFruit_2.0","StewedFruit_3.0","StewedFruit_4.0","StewedFruit_0.0","Prune_1.0","Prune_2.0","Prune_3.0","Prune_4.0","Prune_0.0","DriedFruit_1.0","DriedFruit_2.0","DriedFruit_3.0","DriedFruit_4.0","DriedFruit_0.0","MixFruit_1.0","MixFruit_2.0","MixFruit_3.0","MixFruit_4.0","MixFruit_0.0","Apple_1.0","Apple_2.0","Apple_3.0","Apple_4.0","Apple_0.0","Banana_1.0","Banana_2.0","Banana_3.0","Banana_4.0","Banana_0.0","Berry_1.0","Berry_2.0","Berry_3.0","Berry_4.0","Berry_0.0","Cherry_1.0","Cherry_2.0","Cherry_3.0","Cherry_4.0","Cherry_0.0","Grapefruit_1.0","Grapefruit_2.0","Grapefruit_3.0","Grapefruit_4.0","Grapefruit_0.0","Grape_1.0","Grape_2.0","Grape_3.0","Grape_4.0","Grape_0.0","Mango_1.0","Mango_2.0","Mango_3.0","Mango_4.0","Mango_0.0","Melon_1.0","Melon_2.0","Melon_3.0","Melon_4.0","Melon_0.0","Orange_1.0","Orange_2.0","Orange_3.0","Orange_4.0","Orange_0.0","Satsuma_1.0","Satsuma_2.0","Satsuma_3.0","Satsuma_4.0","Satsuma_0.0","Peach_1.0","Peach_2.0","Peach_3.0","Peach_4.0","Peach_0.0","Pear_1.0","Pear_2.0","Pear_3.0","Pear_4.0","Pear_0.0","Pineapple_1.0","Pineapple_2.0","Pineapple_3.0","Pineapple_4.0","Pineapple_0.0","Plum_1.0","Plum_2.0","Plum_3.0","Plum_4.0","Plum_0.0","OthFruit_1.0","OthFruit_2.0","OthFruit_3.0","OthFruit_4.0","OthFruit_0.0")

# define valid values
valid_egg_values <- c(1, 2, 300, 555)
valid_meat_values <- c(1, 2, 3, 4, 500, 555)
valid_fish_values <- c(1, 2, 3, 400, 555)
valid_vegeAlter_values <- c(1, 2, 3, 400, 555)
valid_vegetable_values <- c(1, 2, 300, 555, 444)
valid_fruit_values <- c(1, 2, 3, 400, 555)
valid_cvalues <- c(0, 1)

# only keep valid values for wanted variables
df[, egg_variables] <- lapply(df[, egg_variables], function(x) ifelse(x %in% valid_egg_values, x, NA))
df[, meat_variables] <- lapply(df[, meat_variables], function(x) ifelse(x %in% valid_meat_values, x, NA))
df[, fish_variables] <- lapply(df[, fish_variables], function(x) ifelse(x %in% valid_fish_values, x, NA))
df[, vegeAlter_variables] <- lapply(df[, vegeAlter_variables], function(x) ifelse(x %in% valid_vegeAlter_values, x, NA))
df[, vegetable_variables] <- lapply(df[, vegetable_variables], function(x) ifelse(x %in% valid_vegetable_values, x, NA))
df[, fruit_variables] <- lapply(df[, fruit_variables], function(x) ifelse(x %in% valid_fruit_values, x, NA))
df[, cvariables] <- lapply(df[, cvariables], function(x) ifelse(x %in% valid_cvalues, x, NA))
# replace values
df[, egg_variables] <- lapply(df[, egg_variables], function(x) { 
    x <- ifelse(x == 555, 0.5, x) 
    x <- ifelse(x == 300, 3, x)
    x
})
df[, meat_variables] <- lapply(df[, meat_variables], function(x) { 
    x <- ifelse(x == 555, 0.5, x) 
    x <- ifelse(x == 500, 5, x)
    x
})
df[, fish_variables] <- lapply(df[, fish_variables], function(x) { 
    x <- ifelse(x == 555, 0.5, x) 
    x <- ifelse(x == 400, 4, x)
    x
})
df[, vegeAlter_variables] <- lapply(df[, vegeAlter_variables], function(x) { 
    x <- ifelse(x == 555, 0.5, x) 
    x <- ifelse(x == 400, 4, x)
    x
})
df[, vegetable_variables] <- lapply(df[, vegetable_variables], function(x) { 
    x <- ifelse(x == 555, 0.5, x) 
    x <- ifelse(x == 300, 3, x)
    x <- ifelse(x == 444, 0.25, x)
    x
})
df[, fruit_variables] <- lapply(df[, fruit_variables], function(x) { 
    x <- ifelse(x == 555, 0.5, x) 
    x <- ifelse(x == 400, 4, x)
    x
})
rm(valid_cvalues, valid_egg_values,valid_fish_values, valid_fruit_values, valid_meat_values, valid_vegeAlter_values, valid_vegetable_values)
# List of variables
variables <- c("WholeEgg","Omelette","EgginSandwich","ScotchEgg","OthEgg","Sausage","Beef","Pork","Lamb","CrumbPoultry","Poultry","Bacon","Ham","Liver","OthMeat","TinTuna","OilyFish","BreadFish","BatteredFish","WhiteFish","Prawns","LobsterCrab","Shellfish","OthFish","VegeSausage","Tofu","Quorn","OthVegeAlter","BakeBean","Pulse","FriedPotato","BoilPotato","MashPotato","MixVege","VegePiece","Coleslaw","SideSalad","Avocado","BroadBean","GreenBean","Beetroot","Broccoli","Butternut","Cabbage","Carrot","Cauliflower","Celery","Courgette","Cucumber","Garlic","Leek","Lettuce","Mushroom","Onion","Parsnip","Pea","Sweetpepper","Spinach","Sprouts","Sweetcorn","Sweetpotato","FreshTomato","TinTomato","Turnip","Watercress","OthVege","StewedFruit","Prune","DriedFruit","MixFruit","Apple","Banana","Berry","Cherry","Grapefruit","Grape","Mango","Melon","Orange","Satsuma","Peach","Pear","Pineapple","Plum","OthFruit")

# Suffix for each variable
suffix <- c("_1.0", "_2.0", "_3.0", "_4.0", "_0.0")
# Loop through all variables
for (var in variables) {
  # Generate the column names for each variable
  cols <- paste0(var, suffix)
  # Check if columns exist in the dataframe
  if (all(cols %in% colnames(df))) {
    # Calculate the mean
    df[[paste0(var, "_mean")]] <- rowMeans(df[, cols], na.rm = TRUE)
  }
}

# merge variables
# 1. merge egg:
egg_vars <- c("WholeEgg","Omelette","EgginSandwich","ScotchEgg","OthEgg")
suffixes <- c("1.0", "2.0", "3.0", "4.0", "0.0")

# calculate bread_* variables
for(suffix in suffixes) {
  columns <- paste(egg_vars, suffix, sep="_") # creates a vector of column names with current suffix
  new_column <- paste("egg", suffix, sep="_") # creates a name for new column
  df[[new_column]] <- apply(df[, columns], 1, function(x) {
    if (all(is.na(x))) {
      return(NA)
    } else {
      return(sum(x, na.rm = TRUE))
    }
  })
}

# Calculate row mean of egg
df$egg_mean <- apply(df[, paste("egg", suffixes, sep="_")], 1, function(x) {
    if (all(is.na(x))) {
      return(NA)
    } else {
      return(mean(x, na.rm = TRUE))
    }
  })

# Remove egg_* columns
df <- df[ , !(names(df) %in% paste("egg", suffixes, sep="_"))]
rm(columns, egg_vars, new_column, suffix)

# merge variables
# 1. merge meat:
meat_vars <- c("Sausage","Beef","Pork","Lamb","CrumbPoultry","Poultry","Bacon","Ham","Liver","OthMeat")
suffixes <- c("1.0", "2.0", "3.0", "4.0", "0.0")

# calculate bread_* variables
for(suffix in suffixes) {
  columns <- paste(meat_vars, suffix, sep="_") # creates a vector of column names with current suffix
  new_column <- paste("meat", suffix, sep="_") # creates a name for new column
  df[[new_column]] <- apply(df[, columns], 1, function(x) {
    if (all(is.na(x))) {
      return(NA)
    } else {
      return(sum(x, na.rm = TRUE))
    }
  })
}

# Calculate row mean of meat
df$meat_mean <- apply(df[, paste("meat", suffixes, sep="_")], 1, function(x) {
    if (all(is.na(x))) {
      return(NA)
    } else {
      return(mean(x, na.rm = TRUE))
    }
  })

# Remove meat_* columns
df <- df[ , !(names(df) %in% paste("meat", suffixes, sep="_"))]
rm(columns, meat_vars, new_column, suffix)

# merge variables
# 1. merge fish:
fish_vars <- c("TinTuna","OilyFish","BreadFish","BatteredFish","WhiteFish","Prawns","LobsterCrab","Shellfish","OthFish")
suffixes <- c("1.0", "2.0", "3.0", "4.0", "0.0")

# calculate bread_* variables
for(suffix in suffixes) {
  columns <- paste(fish_vars, suffix, sep="_") # creates a vector of column names with current suffix
  new_column <- paste("fish", suffix, sep="_") # creates a name for new column
  df[[new_column]] <- apply(df[, columns], 1, function(x) {
    if (all(is.na(x))) {
      return(NA)
    } else {
      return(sum(x, na.rm = TRUE))
    }
  })
}

# Calculate row mean of fish
df$fish_mean <- apply(df[, paste("fish", suffixes, sep="_")], 1, function(x) {
    if (all(is.na(x))) {
      return(NA)
    } else {
      return(mean(x, na.rm = TRUE))
    }
  })

# Remove fish_* columns
df <- df[ , !(names(df) %in% paste("fish", suffixes, sep="_"))]
rm(columns, fish_vars, new_column, suffix)

# merge variables
# 1. merge vegeAlter:
vegeAlter_vars <- c("VegeSausage","Tofu","Quorn","OthVegeAlter")
suffixes <- c("1.0", "2.0", "3.0", "4.0", "0.0")

# calculate bread_* variables
for(suffix in suffixes) {
  columns <- paste(vegeAlter_vars, suffix, sep="_") # creates a vector of column names with current suffix
  new_column <- paste("vegeAlter", suffix, sep="_") # creates a name for new column
  df[[new_column]] <- apply(df[, columns], 1, function(x) {
    if (all(is.na(x))) {
      return(NA)
    } else {
      return(sum(x, na.rm = TRUE))
    }
  })
}

# Calculate row mean of vegealter
df$vegeAlter_mean <- apply(df[, paste("vegeAlter", suffixes, sep="_")], 1, function(x) {
    if (all(is.na(x))) {
      return(NA)
    } else {
      return(mean(x, na.rm = TRUE))
    }
  })

# Remove vegeAlter_* columns
df <- df[ , !(names(df) %in% paste("vegeAlter", suffixes, sep="_"))]
rm(columns, vegeAlter_vars, new_column, suffix)

# merge variables
# 1. merge vegetable:
vegetable_vars <- c("BakeBean","Pulse","FriedPotato","BoilPotato","MashPotato","MixVege","VegePiece","Coleslaw","SideSalad","Avocado","BroadBean","GreenBean","Beetroot","Broccoli","Butternut","Cabbage","Carrot","Cauliflower","Celery","Courgette","Cucumber","Garlic","Leek","Lettuce","Mushroom","Onion","Parsnip","Pea","Sweetpepper","Spinach","Sprouts","Sweetcorn","Sweetpotato","FreshTomato","TinTomato","Turnip","Watercress","OthVege")
suffixes <- c("1.0", "2.0", "3.0", "4.0", "0.0")

# calculate bread_* variables
for(suffix in suffixes) {
  columns <- paste(vegetable_vars, suffix, sep="_") # creates a vector of column names with current suffix
  new_column <- paste("vegetable", suffix, sep="_") # creates a name for new column
  df[[new_column]] <- apply(df[, columns], 1, function(x) {
    if (all(is.na(x))) {
      return(NA)
    } else {
      return(sum(x, na.rm = TRUE))
    }
  })
}

# Calculate row mean of vegetable
df$vegetable_mean <- apply(df[, paste("vegetable", suffixes, sep="_")], 1, function(x) {
    if (all(is.na(x))) {
      return(NA)
    } else {
      return(mean(x, na.rm = TRUE))
    }
  })

# Remove vegetable_* columns
df <- df[ , !(names(df) %in% paste("vegetable", suffixes, sep="_"))]
rm(columns, vegetable_vars, new_column, suffix)

# merge variables
# 1. merge fruit:
fruit_vars <- c("StewedFruit","Prune","DriedFruit","MixFruit","Apple","Banana","Berry","Cherry","Grapefruit","Grape","Mango","Melon","Orange","Satsuma","Peach","Pear","Pineapple","Plum","OthFruit")
suffixes <- c("1.0", "2.0", "3.0", "4.0", "0.0")

# calculate bread_* variables
for(suffix in suffixes) {
  columns <- paste(fruit_vars, suffix, sep="_") # creates a vector of column names with current suffix
  new_column <- paste("fruit", suffix, sep="_") # creates a name for new column
  df[[new_column]] <- apply(df[, columns], 1, function(x) {
    if (all(is.na(x))) {
      return(NA)
    } else {
      return(sum(x, na.rm = TRUE))
    }
  })
}

# Calculate row mean of fruit
df$fruit_mean <- apply(df[, paste("fruit", suffixes, sep="_")], 1, function(x) {
    if (all(is.na(x))) {
      return(NA)
    } else {
      return(mean(x, na.rm = TRUE))
    }
  })

# Remove fruit_* columns
df <- df[ , !(names(df) %in% paste("fruit", suffixes, sep="_"))]
rm(columns, fruit_vars, new_column, suffix)
rm(cols, suffixes, var, variables)
# remove unwanted variables
# variables to remove
n_variables <- c("FatRemoveMeat_1.0", "FatRemoveMeat_2.0", "FatRemoveMeat_3.0", "FatRemoveMeat_4.0", "FatRemoveMeat_0.0", "SkinRemovdPoultry_1.0", "SkinRemovdPoultry_2.0", "SkinRemovdPoultry_3.0", "SkinRemovdPoultry_4.0", "SkinRemovdPoultry_0.0")
variables_to_remove <- c(cvariables, egg_variables, fish_variables, fruit_variables, meat_variables, n_variables, vegetable_variables, vegeAlter_variables)
df <- df %>% select(-one_of(variables_to_remove))
write.csv(df, "C:\\Users\\timothy\\OneDrive\\Documents\\ISU\\food_project\\data\\data_for_test\\food_meat_vegetable.csv",na='',row.names=FALSE)
rm(list=ls())
```

```{r}
# test for liquid and meat_vegetable
# maineffects for liquid data
library(lmerTest)
df<-read.csv(file = 'C:\\Users\\timothy\\OneDrive\\Documents\\ISU\\food_project\\data\\data_for_test\\food_liquids.csv')
# Fit the model
df$APOE_all <- as.factor(df$APOE_all)
df$T40_Gcar <- as.factor(df$T40_Gcar)
df$family_history_AD <- as.factor(df$family_history_AD)
df$Sex <- as.factor(df$Sex)
df$AlcoholY08 <- as.factor(df$AlcoholY08)
df$SmokingY08 <- as.factor(df$SmokingY08)
df$Assessment_0 <- as.factor(df$Assessment_0)
df$EID <- as.factor(df$EID)
results <- data.frame()
# List of variables to test

test_vars <- c("Water_mean", "LowCalorie_mean", "Fizzy_mean", "Squash_mean", "OrangeJuice_mean", "GrapeJuice_mean", "FruitVegeJuice_mean", "FruitSmoothie_mean", "DairySmoothie_mean", "InstantCoffee_mean", "FilterCoffee_mean", "Cappuccino_mean", "Latte_mean", "Espresso_mean", "OtherCoffee_mean", "LowCalorieHotChocolate_mean", "HotChocolate_mean", "StandTea_mean", "RooibosTea_mean", "GreenTea_mean", "HerbalTea_mean", "OtherTea_mean", "juice_mean", "coffee_mean", "tea_mean")

dependent_vars <- c("rsfMRI_Component1", "rsfMRI_Component2",	"rsfMRI_Component3", "rsfMRI_Component4","rsfMRI_Component5", "rsfMRI_Component6", "rsfMRI_Component7", "rsfMRI_Component8", "rsfMRI_Component9", "rsfMRI_Component10", "rsfMRI_Component11", "rsfMRI_Component12", "rsfMRI_Component13", "rsfMRI_Component14", "rsfMRI_Component15", "rsfMRI_Component16", "rsfMRI_Component17",	"rsfMRI_Component18",	"rsfMRI_Component19", "rsfMRI_Component20", "rsfMRI_Component21")

# Double loop through each dependent and test variable and fit the model
for (dep_var in dependent_vars) {
  for (test_var in test_vars) {
  
    # Construct the formula
    formula <- as.formula(paste(dep_var, "~ APOE_all + T40_Gcar + family_history_AD + Age_Baseline + Sex + 
                               BMI_Y08andY12andY14_mean + AlcoholY08 + SmokingY08 + Townsend +", test_var, "+ 
                               (1 | Assessment_0)"))
  
    # Fit the model
    model <- lmer(formula, data = df, REML=FALSE)
    
   # Get the summary
    model_summary <- summary(model)
    
    # Extract the results for the test variable
    estimate <- model_summary$coefficients[test_var, "Estimate"]
    std_error <- model_summary$coefficients[test_var, "Std. Error"]
    p_value <- model_summary$coefficients[test_var, "Pr(>|t|)"]
    
    # Add the results to the data frame
    results <- rbind(results, data.frame(Dependent_Variable = dep_var,
                                         Test_Variable = test_var,
                                         Estimate = estimate,
                                         Std_Error = std_error,
                                         p_value = p_value))
  }
}
write.csv(results, "C:\\Users\\timothy\\OneDrive\\Documents\\ISU\\food_project\\output\\liquids_meat_vege\\maineffect_liquids.csv",na='',row.names=FALSE)
rm(list=ls())

#interaction test for all liquids data
library(lmerTest)
df<-read.csv(file = 'C:\\Users\\timothy\\OneDrive\\Documents\\ISU\\food_project\\data\\data_for_test\\food_liquids.csv')

# Fit the model -- factor all factor variables
factor_vars <- c("AlcoholY08", "SmokingY08", "Assessment_0", "EID")
for (var in factor_vars) {
  df[[var]] <- as.factor(df[[var]])
}
rm(factor_vars,var)

# Scale all continuous variables
scale_vars <- c("Water_mean", "LowCalorie_mean", "Fizzy_mean", "Squash_mean", "OrangeJuice_mean", "GrapeJuice_mean", "FruitVegeJuice_mean", "FruitSmoothie_mean", "DairySmoothie_mean", "InstantCoffee_mean", "FilterCoffee_mean", "Cappuccino_mean", "Latte_mean", "Espresso_mean", "OtherCoffee_mean", "LowCalorieHotChocolate_mean", "HotChocolate_mean", "StandTea_mean", "RooibosTea_mean", "GreenTea_mean", "HerbalTea_mean", "OtherTea_mean", "juice_mean", "coffee_mean", "tea_mean", "rsfMRI_Component1", "rsfMRI_Component2",	"rsfMRI_Component3", "rsfMRI_Component4","rsfMRI_Component5", "rsfMRI_Component6", "rsfMRI_Component7", "rsfMRI_Component8", "rsfMRI_Component9", "rsfMRI_Component10", "rsfMRI_Component11", "rsfMRI_Component12", "rsfMRI_Component13", "rsfMRI_Component14", "rsfMRI_Component15", "rsfMRI_Component16", "rsfMRI_Component17",	"rsfMRI_Component18",	"rsfMRI_Component19", "rsfMRI_Component20", "rsfMRI_Component21", "Age_Baseline", "BMI_Y08andY12andY14_mean")

for (var in scale_vars) {
  df[[var]] <- as.numeric(df[[var]])
}
rm(scale_vars, var)

# Define the dependent variables
dependent_vars <- c("rsfMRI_Component1", "rsfMRI_Component2",	"rsfMRI_Component3", "rsfMRI_Component4","rsfMRI_Component5", "rsfMRI_Component6", "rsfMRI_Component7", "rsfMRI_Component8", "rsfMRI_Component9", "rsfMRI_Component10", "rsfMRI_Component11", "rsfMRI_Component12", "rsfMRI_Component13", "rsfMRI_Component14", "rsfMRI_Component15", "rsfMRI_Component16", "rsfMRI_Component17",	"rsfMRI_Component18",	"rsfMRI_Component19", "rsfMRI_Component20", "rsfMRI_Component21")

# List of variables to test
test_vars <- c("Water_mean", "LowCalorie_mean", "Fizzy_mean", "Squash_mean", "OrangeJuice_mean", "GrapeJuice_mean", "FruitVegeJuice_mean", "FruitSmoothie_mean", "DairySmoothie_mean", "InstantCoffee_mean", "FilterCoffee_mean", "Cappuccino_mean", "Latte_mean", "Espresso_mean", "OtherCoffee_mean", "LowCalorieHotChocolate_mean", "HotChocolate_mean", "StandTea_mean", "RooibosTea_mean", "GreenTea_mean", "HerbalTea_mean", "OtherTea_mean", "juice_mean", "coffee_mean", "tea_mean")

# List of factors
factor_vars <- c("APOE_all", "T40_Gcar", "family_history_AD")

# Initialize a results data frame
results <- data.frame()

# Loop over each dependent variable
for(factor_var in factor_vars) {
 for (dep_var in dependent_vars) {
  for (test_var in test_vars) {
      
    # Construct the formula
    formula <- as.formula(paste(dep_var, "~ APOE_all + T40_Gcar + family_history_AD + Age_Baseline + Sex + 
                               BMI_Y08andY12andY14_mean + AlcoholY08 + SmokingY08 + Townsend +",test_var,"+", factor_var, ":", test_var, "+ 
                               (1 | Assessment_0)"))
  
    # Fit the model
    model <- lmer(formula, data = df, REML=FALSE)

 # Get the summary
    model_summary <- summary(model)
   
    # Extract the results for the interaction term
    interaction_term <- paste(factor_var, test_var, sep=":")
    estimate <- model_summary$coefficients[interaction_term, "Estimate"]
    std_error <- model_summary$coefficients[interaction_term, "Std. Error"]
    p_value <- model_summary$coefficients[interaction_term, "Pr(>|t|)"]

    # Add the results to the data frame
    results <- rbind(results, data.frame(Dependent_Variable = dep_var,
                                         Factors = factor_var,
                                         Test_Variable = test_var,
                                         Estimate = estimate,
                                         Std_Error = std_error,
                                         P_Value = p_value))
    }
  }
}
write.csv(results, "C:\\Users\\timothy\\OneDrive\\Documents\\ISU\\food_project\\output\\liquids_meat_vege\\interactions_liquids.csv",na='',row.names=FALSE)
rm(list=ls())

# maineffects for meat_vege data
library(lmerTest)
df<-read.csv(file = 'C:\\Users\\timothy\\OneDrive\\Documents\\ISU\\food_project\\data\\data_for_test\\food_meat_vegetable.csv')
# Fit the model
df$APOE_all <- as.factor(df$APOE_all)
df$T40_Gcar <- as.factor(df$T40_Gcar)
df$family_history_AD <- as.factor(df$family_history_AD)

df$Sex <- as.factor(df$Sex)
df$AlcoholY08 <- as.factor(df$AlcoholY08)
df$SmokingY08 <- as.factor(df$SmokingY08)
df$Assessment_0 <- as.factor(df$Assessment_0)
df$EID <- as.factor(df$EID)
results <- data.frame()
# List of variables to test

test_vars <- c("WholeEgg_mean", "Omelette_mean", "EgginSandwich_mean", "ScotchEgg_mean", "OthEgg_mean", "Sausage_mean", "Beef_mean", "Pork_mean", "Lamb_mean", "CrumbPoultry_mean", "Poultry_mean", "Bacon_mean", "Ham_mean", "Liver_mean", "OthMeat_mean", "TinTuna_mean", "OilyFish_mean", "BreadFish_mean", "BatteredFish_mean", "WhiteFish_mean", "Prawns_mean", "LobsterCrab_mean", "Shellfish_mean", "OthFish_mean", "VegeSausage_mean", "Tofu_mean", "Quorn_mean", "OthVegeAlter_mean", "BakeBean_mean", "Pulse_mean", "FriedPotato_mean", "BoilPotato_mean", "MashPotato_mean", "MixVege_mean", "VegePiece_mean", "Coleslaw_mean", "SideSalad_mean", "Avocado_mean", "BroadBean_mean", "GreenBean_mean", "Beetroot_mean", "Broccoli_mean", "Butternut_mean", "Cabbage_mean", "Carrot_mean", "Cauliflower_mean", "Celery_mean", "Courgette_mean", "Cucumber_mean", "Garlic_mean", "Leek_mean", "Lettuce_mean", "Mushroom_mean", "Onion_mean", "Parsnip_mean", "Pea_mean", "Sweetpepper_mean", "Spinach_mean", "Sprouts_mean", "Sweetcorn_mean", "Sweetpotato_mean", "FreshTomato_mean", "TinTomato_mean", "Turnip_mean", "Watercress_mean", "OthVege_mean", "StewedFruit_mean", "Prune_mean", "DriedFruit_mean", "MixFruit_mean", "Apple_mean", "Banana_mean", "Berry_mean", "Cherry_mean", "Grapefruit_mean", "Grape_mean", "Mango_mean", "Melon_mean", "Orange_mean", "Satsuma_mean", "Peach_mean", "Pear_mean", "Pineapple_mean", "Plum_mean", "OthFruit_mean", "egg_mean", "meat_mean", "fish_mean", "vegeAlter_mean", "vegetable_mean", "fruit_mean")

dependent_vars <- c("rsfMRI_Component1", "rsfMRI_Component2",	"rsfMRI_Component3", "rsfMRI_Component4","rsfMRI_Component5", "rsfMRI_Component6", "rsfMRI_Component7", "rsfMRI_Component8", "rsfMRI_Component9", "rsfMRI_Component10", "rsfMRI_Component11", "rsfMRI_Component12", "rsfMRI_Component13", "rsfMRI_Component14", "rsfMRI_Component15", "rsfMRI_Component16", "rsfMRI_Component17",	"rsfMRI_Component18",	"rsfMRI_Component19", "rsfMRI_Component20", "rsfMRI_Component21")


# Double loop through each dependent and test variable and fit the model
for (dep_var in dependent_vars) {
  for (test_var in test_vars) {
  
    # Construct the formula
    formula <- as.formula(paste(dep_var, "~ APOE_all + T40_Gcar + family_history_AD + Age_Baseline + Sex + 
                               BMI_Y08andY12andY14_mean + AlcoholY08 + SmokingY08 + Townsend +", test_var, "+ 
                               (1 | Assessment_0)"))
  
    # Fit the model
    model <- lmer(formula, data = df, REML=FALSE)
    
   # Get the summary
    model_summary <- summary(model)
    
    # Extract the results for the test variable
    estimate <- model_summary$coefficients[test_var, "Estimate"]
    std_error <- model_summary$coefficients[test_var, "Std. Error"]
    p_value <- model_summary$coefficients[test_var, "Pr(>|t|)"]
    
    # Add the results to the data frame
    results <- rbind(results, data.frame(Dependent_Variable = dep_var,
                                         Test_Variable = test_var,
                                         Estimate = estimate,
                                         Std_Error = std_error,
                                         p_value = p_value))
  }
}
write.csv(results, "C:\\Users\\timothy\\OneDrive\\Documents\\ISU\\food_project\\output\\liquids_meat_vege\\maineffect_meat_vege.csv",na='',row.names=FALSE)
rm(list=ls())

#interaction test for all meat_vegetable data
library(lmerTest)
df<-read.csv(file = 'C:\\Users\\timothy\\OneDrive\\Documents\\ISU\\food_project\\data\\data_for_test\\food_meat_vegetable.csv')

# Fit the model -- factor all factor variables
factor_vars <- c("AlcoholY08", "SmokingY08", "Assessment_0", "EID")
for (var in factor_vars) {
  df[[var]] <- as.factor(df[[var]])
}
rm(factor_vars,var)

# Scale all continuous variables
scale_vars <- c("WholeEgg_mean", "Omelette_mean", "EgginSandwich_mean", "ScotchEgg_mean", "OthEgg_mean", "Sausage_mean", "Beef_mean", "Pork_mean", "Lamb_mean", "CrumbPoultry_mean", "Poultry_mean", "Bacon_mean", "Ham_mean", "Liver_mean", "OthMeat_mean", "TinTuna_mean", "OilyFish_mean", "BreadFish_mean", "BatteredFish_mean", "WhiteFish_mean", "Prawns_mean", "LobsterCrab_mean", "Shellfish_mean", "OthFish_mean", "VegeSausage_mean", "Tofu_mean", "Quorn_mean", "OthVegeAlter_mean", "BakeBean_mean", "Pulse_mean", "FriedPotato_mean", "BoilPotato_mean", "MashPotato_mean", "MixVege_mean", "VegePiece_mean", "Coleslaw_mean", "SideSalad_mean", "Avocado_mean", "BroadBean_mean", "GreenBean_mean", "Beetroot_mean", "Broccoli_mean", "Butternut_mean", "Cabbage_mean", "Carrot_mean", "Cauliflower_mean", "Celery_mean", "Courgette_mean", "Cucumber_mean", "Garlic_mean", "Leek_mean", "Lettuce_mean", "Mushroom_mean", "Onion_mean", "Parsnip_mean", "Pea_mean", "Sweetpepper_mean", "Spinach_mean", "Sprouts_mean", "Sweetcorn_mean", "Sweetpotato_mean", "FreshTomato_mean", "TinTomato_mean", "Turnip_mean", "Watercress_mean", "OthVege_mean", "StewedFruit_mean", "Prune_mean", "DriedFruit_mean", "MixFruit_mean", "Apple_mean", "Banana_mean", "Berry_mean", "Cherry_mean", "Grapefruit_mean", "Grape_mean", "Mango_mean", "Melon_mean", "Orange_mean", "Satsuma_mean", "Peach_mean", "Pear_mean", "Pineapple_mean", "Plum_mean", "OthFruit_mean", "egg_mean", "meat_mean", "fish_mean", "vegeAlter_mean", "vegetable_mean", "fruit_mean", "rsfMRI_Component1", "rsfMRI_Component2",	"rsfMRI_Component3", "rsfMRI_Component4","rsfMRI_Component5", "rsfMRI_Component6", "rsfMRI_Component7", "rsfMRI_Component8", "rsfMRI_Component9", "rsfMRI_Component10", "rsfMRI_Component11", "rsfMRI_Component12", "rsfMRI_Component13", "rsfMRI_Component14", "rsfMRI_Component15", "rsfMRI_Component16", "rsfMRI_Component17",	"rsfMRI_Component18",	"rsfMRI_Component19", "rsfMRI_Component20", "rsfMRI_Component21", "Age_Baseline", "BMI_Y08andY12andY14_mean")

for (var in scale_vars) {
  df[[var]] <- as.numeric(df[[var]])
}
rm(scale_vars, var)

# Define the dependent variables
dependent_vars <- c("rsfMRI_Component1", "rsfMRI_Component2",	"rsfMRI_Component3", "rsfMRI_Component4","rsfMRI_Component5", "rsfMRI_Component6", "rsfMRI_Component7", "rsfMRI_Component8", "rsfMRI_Component9", "rsfMRI_Component10", "rsfMRI_Component11", "rsfMRI_Component12", "rsfMRI_Component13", "rsfMRI_Component14", "rsfMRI_Component15", "rsfMRI_Component16", "rsfMRI_Component17",	"rsfMRI_Component18",	"rsfMRI_Component19", "rsfMRI_Component20", "rsfMRI_Component21")

# List of variables to test
test_vars <- c("WholeEgg_mean", "Omelette_mean", "EgginSandwich_mean", "ScotchEgg_mean", "OthEgg_mean", "Sausage_mean", "Beef_mean", "Pork_mean", "Lamb_mean", "CrumbPoultry_mean", "Poultry_mean", "Bacon_mean", "Ham_mean", "Liver_mean", "OthMeat_mean", "TinTuna_mean", "OilyFish_mean", "BreadFish_mean", "BatteredFish_mean", "WhiteFish_mean", "Prawns_mean", "LobsterCrab_mean", "Shellfish_mean", "OthFish_mean", "VegeSausage_mean", "Tofu_mean", "Quorn_mean", "OthVegeAlter_mean", "BakeBean_mean", "Pulse_mean", "FriedPotato_mean", "BoilPotato_mean", "MashPotato_mean", "MixVege_mean", "VegePiece_mean", "Coleslaw_mean", "SideSalad_mean", "Avocado_mean", "BroadBean_mean", "GreenBean_mean", "Beetroot_mean", "Broccoli_mean", "Butternut_mean", "Cabbage_mean", "Carrot_mean", "Cauliflower_mean", "Celery_mean", "Courgette_mean", "Cucumber_mean", "Garlic_mean", "Leek_mean", "Lettuce_mean", "Mushroom_mean", "Onion_mean", "Parsnip_mean", "Pea_mean", "Sweetpepper_mean", "Spinach_mean", "Sprouts_mean", "Sweetcorn_mean", "Sweetpotato_mean", "FreshTomato_mean", "TinTomato_mean", "Turnip_mean", "Watercress_mean", "OthVege_mean", "StewedFruit_mean", "Prune_mean", "DriedFruit_mean", "MixFruit_mean", "Apple_mean", "Banana_mean", "Berry_mean", "Cherry_mean", "Grapefruit_mean", "Grape_mean", "Mango_mean", "Melon_mean", "Orange_mean", "Satsuma_mean", "Peach_mean", "Pear_mean", "Pineapple_mean", "Plum_mean", "OthFruit_mean", "egg_mean", "meat_mean", "fish_mean", "vegeAlter_mean", "vegetable_mean", "fruit_mean")

# List of factors
factor_vars <- c("APOE_all", "T40_Gcar", "family_history_AD")

# Initialize a results data frame
results <- data.frame()

# Loop over each dependent variable
for(factor_var in factor_vars) {
 for (dep_var in dependent_vars) {
  for (test_var in test_vars) {
      
    # Construct the formula
    formula <- as.formula(paste(dep_var, "~ APOE_all + T40_Gcar + family_history_AD + Age_Baseline + Sex + 
                               BMI_Y08andY12andY14_mean + AlcoholY08 + SmokingY08 + Townsend +",test_var,"+", factor_var, ":", test_var, "+ 
                               (1 | Assessment_0)"))
  
    # Fit the model
    model <- lmer(formula, data = df, REML=FALSE)

 # Get the summary
    model_summary <- summary(model)
   
    # Extract the results for the interaction term
    interaction_term <- paste(factor_var, test_var, sep=":")
    estimate <- model_summary$coefficients[interaction_term, "Estimate"]
    std_error <- model_summary$coefficients[interaction_term, "Std. Error"]
    p_value <- model_summary$coefficients[interaction_term, "Pr(>|t|)"]

    # Add the results to the data frame
    results <- rbind(results, data.frame(Dependent_Variable = dep_var,
                                         Factors = factor_var,
                                         Test_Variable = test_var,
                                         Estimate = estimate,
                                         Std_Error = std_error,
                                         P_Value = p_value))
    }
  }
}
write.csv(results, "C:\\Users\\timothy\\OneDrive\\Documents\\ISU\\food_project\\output\\liquids_meat_vege\\interactions_meat_vege.csv",na='',row.names=FALSE)
rm(list=ls())
```


```{r}
# the following code is used to re-range the raw output (maineffects)

df<-read.csv(file = 'C:\\Users\\timothy\\OneDrive\\Documents\\ISU\\food_project\\data\\data_for_test\\sort\\01.csv')
library(tidyverse)

# Calculate the number of groups
num_groups <- nrow(df) / 21

# Create a grouping variable
df$group <- rep(1:num_groups, each=21)

# Reshape the data
df_wide <- df %>%
  group_by(group) %>%
  mutate(row_in_group = row_number()) %>%
  pivot_wider(
    id_cols = row_in_group,
    names_from = group,
    values_from = c(Estimate, Std_Error, p_value),
    names_glue = "{.value}_Group{group}"
  )

# Arrange columns in the desired order
col_order <- c(rbind(
  paste0("Estimate_Group", 1:num_groups),
  paste0("Std_Error_Group", 1:num_groups),
  paste0("p_value_Group", 1:num_groups)
))

df_wide <- df_wide %>% select(all_of(col_order))

# View the result
write.csv(df_wide, "C:\\Users\\timothy\\OneDrive\\Documents\\ISU\\food_project\\data\\data_for_test\\sort\\02.csv",na='',row.names=FALSE)

```

```{r}
# the following code is used to re-range the raw output (interactions) because in the interactions tests, the std error is not in the summary

df<-read.csv(file = 'C:\\Users\\timothy\\OneDrive\\Documents\\ISU\\food_project\\data\\data_for_test\\sort\\01.csv')
library(tidyverse)

# Calculate the number of groups
num_groups <- nrow(df) / 21

# Create a grouping variable
df$group <- rep(1:num_groups, each=21)

# Reshape the data
df_wide <- df %>%
  group_by(group) %>%
  mutate(row_in_group = row_number()) %>%
  pivot_wider(
    id_cols = row_in_group,
    names_from = group,
    values_from = c(Estimate, P_Value),
    names_glue = "{.value}_Group{group}"
  )

# Arrange columns in the desired order
col_order <- c(rbind(
  paste0("Estimate_Group", 1:num_groups),
  paste0("P_Value_Group", 1:num_groups)
))

df_wide <- df_wide %>% select(all_of(col_order))

# View the result
write.csv(df_wide, "C:\\Users\\timothy\\OneDrive\\Documents\\ISU\\food_project\\data\\data_for_test\\sort\\02.csv",na='',row.names=FALSE)
rm(list=ls())
```

